name: medical_data_accounting_system
description: Diploma Avdeenko Yury Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter_facebook_auth: ^4.4.0+1
  crypto: ^3.0.2
  sign_in_with_apple: ^4.1.0
  google_sign_in: ^5.4.0
  fluttertoast: ^8.0.9
  firebase_auth: ^3.5.0
  equatable: ^2.0.0
  core:
    path: core
  core_ui:
    path: core_ui
  domain:
    path: domain
  di:
    path: di
  firebase_core: ^1.24.0
  cloud_firestore: ^3.4.0
  firebase_core_platform_interface: 4.5.1
  provider: ^6.0.3
  flutter:
    sdk: flutter
  data:
    path: data

  auth:
    path: features/auth
  home:
    path: features/home

  cupertino_icons: ^1.0.2
  connectivity_plus: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.7.2

flutter:
  uses-material-design: true
  assets:
    # translations
    - assets/translations/en-US.json
    # images
    - assets/images/image-jeremy.png
    - assets/images/flutter_logo.png
    - assets/images/google_icon.png
    - assets/images/apple_logo.png
    - assets/images/facebook_logo.png
  #fonts
  fonts:
    - family: Rubic
      fonts:
        - asset: assets/fonts/rubic/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/rubic/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/rubic/Rubik-Medium.ttf
          weight: 500