name: domain

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  firebase_auth: ^3.5.0
  equatable: ^2.0.0
  data:
    path: ../data
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.0
  provider: ^6.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
